# Generated by Django 4.2.3 on 2023-07-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipient_name', models.CharField(max_length=20)),
                ('Recipient_phone', models.BigIntegerField()),
                ('Delivery_address', models.CharField(max_length=100)),
                ('Delivery_date', models.DateTimeField()),
                ('Delivery_status', models.CharField(max_length=34)),
            ],
        ),
    ]
